[package]
name = "dashtool-common"
version = "0.2.0"
edition = "2021"

description = "Common functionality for dashtool"

license = "Apache-2.0"

repository = "https://github.com/dashbook/dashtool"

[dependencies]
serde = { workspace = true, features = ["derive"] }
